server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          - gateway:
            route:
              RouteDefinitionLocator: INFO
          - gateway: TRACE

spring:
  cloud:
    gateway:
      routes:
        #medecin-service API
        - id: medecin-service
          uri: lb://medecin-service
          predicates:
            - Path= /api/medecin/**
        #patient-service API
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path= /api/patient/**
        #user-service API
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path= /api/user/**
        #porte-service API
        - id: porte-service
          uri: lb://porte-service
          predicates:
            - Path= /api/porte/**

        #orderLine-service API
        - id: orderLine-service
          uri: lb://orderLine-service
          predicates:
            - Path= /api/orderLine/**

        #order-service API
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path= /api/order/**

        #medicament-service API
        - id: medicament-service
          uri: lb://medicament-service
          predicates:
            - Path= /api/medicament-service

  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: http://localhost:8080/realms/clinic-realm
          jwk-set-url: ${spring.security.oauth2.resourceServer.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: user-service
      principal-attribute: preferred_name
